# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
workspace 'TokoQ'

target 'TokoQ' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!
  use_modular_headers!
  inhibit_all_warnings!

  # Pods for TokoQ
  pod 'FLEX', :configurations => ['Debug']

  target 'TokoQTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TokoQUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
